In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
df = pd.read_csv('/content/Churn_Modelling_With_Nulls.csv')
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      9500 non-null   float64
 4   Geography        9500 non-null   object 
 5   Gender           10000 non-null  object 
 6   Age              9500 non-null   float64
 7   Tenure           10000 non-null  int64  
 8   Balance          9500 non-null   float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  9500 non-null   float64
 13  Exited           10000 non-null  int64  
dtypes: float64(4), int64(7), object(3)
memory usage: 1.1+ MB


RowNumber  CustomerId   Surname  CreditScore Geography  Gender   Age  \
0          1    15634602  Hargrave        619.0    France  Female  42.0   
1          2    15647311      Hill        608.0     Spain  Female  41.0   
2          3    15619304      Onio        502.0    France  Female  42.0   
3          4    15701354      Boni          NaN    France  Female  39.0   
4          5    15737888  Mitchell        850.0     Spain  Female  43.0   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [24]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

In [25]:
df.describe()

RowNumber    CustomerId  CreditScore          Age        Tenure  \
count  10000.00000  1.000000e+04  9500.000000  9500.000000  10000.000000   
mean    5000.50000  1.569094e+07   650.970737    38.927263      5.012800   
std     2886.89568  7.193619e+04    96.377164    10.471748      2.892174   
min        1.00000  1.556570e+07   350.000000    18.000000      0.000000   
25%     2500.75000  1.562853e+07   584.000000    32.000000      3.000000   
50%     5000.50000  1.569074e+07   652.000000    37.000000      5.000000   
75%     7500.25000  1.575323e+07   718.000000    44.000000      7.000000   
max    10000.00000  1.581569e+07   850.000000    92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count    9500.000000   10000.000000  10000.00000    10000.000000   
mean    76347.259142       1.530200      0.70550        0.515100   
std     62399.992682       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97079.410000       1.000000      1.00000        1.000000   
75%    127540.252500       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count      9500.000000  10000.000000  
mean     100118.361140      0.203700  
std       57521.198189      0.402769  
min          11.580000      0.000000  
25%       51136.837500      0.000000  
50%      100238.110000      0.000000  
75%      149507.082500      0.000000  
max      199970.740000      1.000000

In [26]:
newdf = pd.DataFrame(df,columns=['CreditScore','Tenure','Balance'])
newdf.info()
newdf.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   CreditScore  9500 non-null   float64
 1   Tenure       10000 non-null  int64  
 2   Balance      9500 non-null   float64
dtypes: float64(2), int64(1)
memory usage: 234.5 KB


CreditScore  Tenure    Balance
0        619.0       2       0.00
1        608.0       1   83807.86
2        502.0       8  159660.80
3          NaN       1       0.00
4        850.0       2  125510.82

In [29]:
newdf['Balance'] = newdf['Balance'].fillna(method='bfill')
newdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   CreditScore  9500 non-null   float64
 1   Tenure       10000 non-null  int64  
 2   Balance      10000 non-null  float64
dtypes: float64(2), int64(1)
memory usage: 234.5 KB


<ipython-input-29-2ad237f63b77>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  newdf['Balance'] = newdf['Balance'].fillna(method='bfill')


In [30]:
newdf['CreditScore']=newdf['CreditScore'].fillna(newdf['CreditScore'].mean())
newdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   CreditScore  10000 non-null  float64
 1   Tenure       10000 non-null  int64  
 2   Balance      10000 non-null  float64
dtypes: float64(2), int64(1)
memory usage: 234.5 KB


In [31]:
# MIN MAX scaling method

scaler = MinMaxScaler()
minmaxdf = scaler.fit_transform(newdf)
print(minmaxdf)

[[0.538      0.2        0.        ]
 [0.516      0.1        0.33403148]
 [0.304      0.8        0.63635718]
 ...
 [0.718      0.7        0.        ]
 [0.844      0.3        0.29922631]
 [0.884      0.4        0.51870777]]


In [32]:
# standard scalar method

scaler = StandardScaler()
scaledf = scaler.fit_transform(newdf)
print(scaledf)

[[-0.34036082 -1.04175968 -1.22391622]
 [-0.45746694 -1.38753759  0.11911277]
 [-1.58594412  1.03290776  1.3346634 ]
 ...
 [ 0.61778018  0.68712986 -1.22391622]
 [ 1.28847888 -0.69598177 -0.02082718]
 [ 1.5013991  -0.35020386  0.86163446]]
